"""empty message

Revision ID: 066941cf3397
Revises: 30cd498d3297
Create Date: 2017-11-14 13:25:29.471492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066941cf3397'
down_revision = '30cd498d3297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashrate_stat', sa.Column('created_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashrate_stat', 'created_at')
    # ### end Alembic commands ###
