"""empty message

Revision ID: 30cd498d3297
Revises: 
Create Date: 2017-11-14 12:42:13.411722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cd498d3297'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashrate_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relayed_by', sa.String(length=64), nullable=True),
    sa.Column('count', sa.String(length=64), nullable=True),
    sa.Column('pool_share', sa.Numeric(precision=36, scale=14), nullable=True),
    sa.Column('hash_share', sa.Numeric(precision=36, scale=14), nullable=True),
    sa.Column('link', sa.String(length=1028), nullable=True),
    sa.Column('pool_id', sa.String(length=64), nullable=True),
    sa.Column('real_hashrate', sa.String(length=64), nullable=True),
    sa.Column('diff_24h', sa.Numeric(precision=36, scale=14), nullable=True),
    sa.Column('pool_icon_class', sa.String(length=1028), nullable=True),
    sa.Column('icon_link', sa.String(length=1028), nullable=True),
    sa.Column('hashrate', sa.Numeric(precision=36, scale=14), nullable=True),
    sa.Column('hashrate_unit', sa.String(length=16), nullable=True),
    sa.Column('lucky', sa.Numeric(precision=36, scale=14), nullable=True),
    sa.Column('cur2max_percent', sa.Numeric(precision=36, scale=14), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashrate_stat')
    # ### end Alembic commands ###
