"""empty message

Revision ID: a3647e779861
Revises: 066941cf3397
Create Date: 2017-11-16 18:25:33.342457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3647e779861'
down_revision = '066941cf3397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osc_otc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_currency', sa.String(length=64), nullable=True),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('trade_currency', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_buy', sa.Boolean(), nullable=True),
    sa.Column('max_qty', sa.Integer(), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=True),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.Column('min_amount', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('group_label', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osc_otc_created_at'), 'osc_otc', ['created_at'], unique=False)
    op.create_index(op.f('ix_osc_otc_group_label'), 'osc_otc', ['group_label'], unique=False)
    op.create_index(op.f('ix_hashrate_stat_created_at'), 'hashrate_stat', ['created_at'], unique=False)
    op.drop_index('idx_created_at', table_name='hashrate_stat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_created_at', 'hashrate_stat', ['created_at'], unique=False)
    op.drop_index(op.f('ix_hashrate_stat_created_at'), table_name='hashrate_stat')
    op.drop_index(op.f('ix_osc_otc_group_label'), table_name='osc_otc')
    op.drop_index(op.f('ix_osc_otc_created_at'), table_name='osc_otc')
    op.drop_table('osc_otc')
    # ### end Alembic commands ###
