"""empty message

Revision ID: d663c786e4a3
Revises: 0223ce4bf5f2
Create Date: 2017-11-26 12:36:49.597490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd663c786e4a3'
down_revision = '0223ce4bf5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osc_turnover', sa.Column('created_at', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_osc_turnover_createTime'), 'osc_turnover', ['createTime'], unique=False)
    op.create_index(op.f('ix_osc_turnover_created_at'), 'osc_turnover', ['created_at'], unique=False)
    op.drop_index('ix_osc_turnover_createTime', table_name='osc_turnover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_osc_turnover_createTime', 'osc_turnover', ['createTime'], unique=False)
    op.drop_index(op.f('ix_osc_turnover_created_at'), table_name='osc_turnover')
    op.drop_index(op.f('ix_osc_turnover_createTime'), table_name='osc_turnover')
    op.drop_column('osc_turnover', 'created_at')
    # ### end Alembic commands ###
