"""empty message

Revision ID: e83496f770b7
Revises: d663c786e4a3
Create Date: 2017-11-26 12:46:08.124216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83496f770b7'
down_revision = 'd663c786e4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osc_turnover', sa.Column('created_at', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_osc_turnover_created_at'), 'osc_turnover', ['created_at'], unique=False)
    op.drop_index('ix_osc_turnover_createTime', table_name='osc_turnover')
    op.drop_column('osc_turnover', 'createTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osc_turnover', sa.Column('createTime', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_osc_turnover_createTime', 'osc_turnover', ['createTime'], unique=False)
    op.drop_index(op.f('ix_osc_turnover_created_at'), table_name='osc_turnover')
    op.drop_column('osc_turnover', 'created_at')
    # ### end Alembic commands ###
